name: BCOL API CHECK CI

on:
  pull_request:
    branches:
      - development
    paths:
      - "bcol-api/**"

jobs:
  bcol-api-check:
    runs-on: ubuntu-latest
    if: github.repository == 'bcgov/sbc-pay'
    env:
      FLASK_ENV: "testing"
      JWT_OIDC_ISSUER: "http://localhost:8081/auth/realms/demo"
      JWT_OIDC_WELL_KNOWN_CONFIG: "http://localhost:8081/auth/realms/demo/.well-known/openid-configuration"
      JWT_OIDC_ALGORITHMS: "RS256"
      JWT_OIDC_AUDIENCE: "sbc-auth-web"
      JWT_OIDC_CLIENT_SECRET: "1111111111"
      JWT_OIDC_JWKS_CACHE_TIMEOUT: "6000"

      BCOL_QUERY_PROFILE_WSDL_URL: "https://appsd1.bconline.gov.bc.ca/access/services/QueryProfile/wsdl/QueryProfile.wsdl"
      BCOL_PAYMENTS_WSDL_URL: "https://appsd1.bconline.gov.bc.ca/account/services/DebitAccount/wsdl/DebitAccount.wsdl"
      BCOL_LDAP_SERVER: "fake"
      BCOL_LDAP_USER_DN_PATTERN: "fake"
      BCOL_DEBIT_ACCOUNT_VERSION: "fake"
      BCOL_LINK_CODE: "000"

    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: ./bcol-api
        run: |
          sudo apt install libsasl2-dev libldap2-dev libssl-dev --yes
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements/dev.txt
      - name: Lint with pylint
        working-directory: ./bcol-api
        run: |
          pylint --rcfile=setup.cfg --load-plugins=pylint_flask --disable=C0301,W0511 src/bcol_api
      - name: Lint with flake8
        working-directory: ./bcol-api
        run: |
          flake8 src/bcol_api tests
      - name: Test with pytest
        working-directory: ./bcol-api
        run: |
          pip install .
          export PYTHONPATH=./src/
          pytest
